add rqt instructions (#1)
moevm/mse_indefinite_nav_cv pull request #9
Opened 2022-03-09 12:33 UTC by sttie

Relates: https://github.com/moevm/mse_indefinite_nav_cv/issues/1

2022-03-10 16:45 UTC, AndrewGavril approved these changes

2022-03-11 12:14 UTC, Gizzatovamir approved these changes

2022-04-04 12:13 UTC, AndrewGavril requested changes
Перенести документ в папку wiki

2022-04-26 20:50 UTC, AndrewGavril approved these changes

2022-04-26 20:50 UTC, merged